package com.lcl.myspring.homework.entity;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.name
     *
     * @mbggenerated
     */
    private Integer name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.adress
     *
     * @mbggenerated
     */
    private String adress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.season
     *
     * @mbggenerated
     */
    private String season;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.name
     *
     * @return the value of order_info.name
     *
     * @mbggenerated
     */
    public Integer getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.name
     *
     * @param name the value for order_info.name
     *
     * @mbggenerated
     */
    public void setName(Integer name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.adress
     *
     * @return the value of order_info.adress
     *
     * @mbggenerated
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.adress
     *
     * @param adress the value for order_info.adress
     *
     * @mbggenerated
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.season
     *
     * @return the value of order_info.season
     *
     * @mbggenerated
     */
    public String getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.season
     *
     * @param season the value for order_info.season
     *
     * @mbggenerated
     */
    public void setSeason(String season) {
        this.season = season == null ? null : season.trim();
    }
}