package com.lcl.myspring.homework.dto;

import com.lcl.myspring.homework.enums.TriggerStatusEnum;
import lombok.Data;

import java.util.Date;

@Data
public class XxlJobInfoDTO {
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.job_group
     *
     * @mbggenerated
     */
    private Integer jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.job_desc
     *
     * @mbggenerated
     */
    private String jobDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.alarm_email
     *
     * @mbggenerated
     */
    private String alarmEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.schedule_type
     *
     * @mbggenerated
     */
    private String scheduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.schedule_conf
     *
     * @mbggenerated
     */
    private String scheduleConf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.misfire_strategy
     *
     * @mbggenerated
     */
    private String misfireStrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.executor_route_strategy
     *
     * @mbggenerated
     */
    private String executorRouteStrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.executor_handler
     *
     * @mbggenerated
     */
    private String executorHandler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.executor_param
     *
     * @mbggenerated
     */
    private String executorParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.executor_block_strategy
     *
     * @mbggenerated
     */
    private String executorBlockStrategy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.executor_timeout
     *
     * @mbggenerated
     */
    private Integer executorTimeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.executor_fail_retry_count
     *
     * @mbggenerated
     */
    private Integer executorFailRetryCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.glue_type
     *
     * @mbggenerated
     */
    private String glueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.glue_remark
     *
     * @mbggenerated
     */
    private String glueRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.glue_updatetime
     *
     * @mbggenerated
     */
    private Date glueUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.child_jobid
     *
     * @mbggenerated
     */
    private String childJobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.trigger_status
     *
     * @mbggenerated
     */
    private TriggerStatusEnum triggerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.trigger_last_time
     *
     * @mbggenerated
     */
    private Long triggerLastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.trigger_next_time
     *
     * @mbggenerated
     */
    private Long triggerNextTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xxl_job_info.glue_source
     *
     * @mbggenerated
     */
    private String glueSource;
}
