package com.lcl.mysqldemo.entity.db01;

import lombok.Data;

@Data
public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.name
     *
     * @mbggenerated
     */
    private Integer name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.adress
     *
     * @mbggenerated
     */
    private String adress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.season
     *
     * @mbggenerated
     */
    private String season;


}