package com.lcl.myspring.homework.mapper;

import com.lcl.myspring.homework.entity.XxlJobInfo;
import com.lcl.myspring.homework.entity.XxlJobInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface XxlJobInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int countByExample(XxlJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int deleteByExample(XxlJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int insert(XxlJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int insertSelective(XxlJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    List<XxlJobInfo> selectByExampleWithBLOBs(XxlJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    List<XxlJobInfo> selectByExample(XxlJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    XxlJobInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") XxlJobInfo record, @Param("example") XxlJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") XxlJobInfo record, @Param("example") XxlJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") XxlJobInfo record, @Param("example") XxlJobInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XxlJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(XxlJobInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xxl_job_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XxlJobInfo record);
}